// Generates REVIEW.md — every staging rule in the app, with its citation, in a
// form a clinician can check against the AJCC manual without reading any code.
//
//   node test/make-review.js > REVIEW.md
//
// Regenerate this whenever data/ changes. It is the artefact a faculty reviewer
// signs off, so it must always match what the app actually computes: it is
// generated from the same modules the app imports, never written by hand.

import { SITES, AJCC_REFERENCE } from '../data/sites.js';
import { survivalFor } from '../data/survival.js';
import { specFor, stageRulesFor, basesFor, specBranches, basisIsMeaningful } from '../engine.js';

const out = [];
const w = (s = '') => out.push(s);

const fmt = (c) => (c === undefined || c === '*' ? 'any' : c.join(', '));

w('# Staging rule review');
w();
w('Generated by `node test/make-review.js`. Do not edit by hand — regenerate it.');
w();
w(`Every rule the app uses is listed below with the source it is cited to. Rules are evaluated
**in the order shown, first match wins**, which mirrors how the printed AJCC tables read.`);
w();
w(`**Edition currency:** [${AJCC_REFERENCE.text}](${AJCC_REFERENCE.url}) — checked ${AJCC_REFERENCE.checked}.`);
w();
w('**Educational use only.** Not for clinical practice.');
w();

// Sites that were not verifiable against the source deck get called out first,
// because those are the ones a reviewer should read most carefully.
const unverified = SITES.filter((s) => s.deckVerified === false);
const caveats = SITES.filter((s) => s.stageGroupCaveat);

w('## Read these first');
w();
if (unverified.length) {
  w('### Not verified against the source deck');
  w();
  w('`HN_staging.pptx` contained no slide for these chapters. Their rules come from AJCC and NCI PDQ, but there is no second copy in the supplied material to check them against:');
  w();
  for (const s of unverified) w(`- **${s.name}** (chapter ${s.chapter})`);
  w();
}
if (caveats.length) {
  w('### Open questions');
  w();
  for (const s of caveats) w(`- **${s.name}** — ${s.stageGroupCaveat}`);
  w();
}

w('## Contents');
w();
for (const s of SITES) {
  w(`- [${s.name}](#${s.id}) — chapter ${s.chapter}, ${s.edition.label}`);
}
w();

for (const site of SITES) {
  w(`<a id="${site.id}"></a>`);
  w();
  w(`## ${site.name}`);
  w();
  w(`| | |`);
  w(`|---|---|`);
  w(`| AJCC chapter | ${site.chapter} |`);
  w(`| Edition | **${site.edition.label}**, effective ${site.edition.effective} |`);
  w(`| Staging bases | ${basesFor(site).join(', ')}${basisIsMeaningful(site) ? '' : ' (identical — no toggle shown)'} |`);
  w(`| Verified against source deck | ${site.deckVerified === false ? '**No**' : 'Yes'} |`);
  w();
  w(`**Staging system:** ${site.citations.ajcc.text}  `);
  w(`<${site.citations.ajcc.url}>`);
  w();
  for (const p of site.citations.papers) {
    w(`**Publication:** ${p.text}${p.doi ? ` doi:${p.doi}` : ''}${p.pmid ? ` PMID:${p.pmid}` : ''}  `);
    if (p.url) w(`<${p.url}>`);
    w();
  }
  if (site.citations.sourcingNote) {
    w(`> **Sourcing note.** ${site.citations.sourcingNote}`);
    w();
  }
  if (site.citations.asProvided) {
    w(`*As provided in the source deck:* ${site.citations.asProvided.text} — <${site.citations.asProvided.url}>`);
    w();
  }
  if (site.stageGroupCaveat) {
    w(`> **Open question.** ${site.stageGroupCaveat}`);
    w();
  }

  if (site.preQuestions?.length) {
    w('### Questions asked before T/N/M');
    w();
    for (const q of site.preQuestions) {
      w(`**${q.prompt}**${q.help ? ` — ${q.help}` : ''}`);
      w();
      for (const o of q.options) {
        w(`- \`${o.value}\` ${o.label}${o.detail ? ` — ${o.detail}` : ''}${o.redirect ? ` _(routes to ${o.redirect})_` : ''}`);
      }
      w();
    }
  }

  // Category definitions, per axis and per basis where they differ.
  for (const axis of ['T', 'N', 'M']) {
    const perBasis = new Map();
    for (const basis of basesFor(site)) {
      const spec = specFor(site, axis, basis);
      if (!spec) continue;
      perBasis.set(site.axes[axis].shared ? 'both' : basis, spec);
    }
    for (const [basisLabel, spec] of perBasis) {
      const heading =
        basisLabel === 'both' ? `### ${axis} categories` : `### ${axis} categories — ${basisLabel}`;
      w(heading);
      w();
      for (const { spec: leaf, pre } of specBranches(spec)) {
        if (Object.keys(pre).length) {
          w(`**When ${Object.entries(pre).map(([k, v]) => `${k} = ${v}`).join(', ')}:**`);
          w();
        }
        w('| Category | Criteria | Source |');
        w('|---|---|---|');
        const items = leaf.kind === 'direct' ? leaf.options : leaf.rules;
        for (const it of items) {
          const label = leaf.kind === 'direct' ? it.value : it.value;
          const criteria = (it.detail || it.label || '').replace(/\|/g, '\\|');
          w(`| \`${label}\` | ${criteria} | ${it.source} |`);
        }
        w();
        if (leaf.kind === 'derived') {
          w('<details><summary>Questions asked to derive this category</summary>');
          w();
          for (const step of leaf.steps) {
            w(`- **${step.prompt}** (\`${step.id}\`)${step.skipWhen ? ` — skipped when ${JSON.stringify(step.skipWhen)}` : ''}`);
            for (const o of step.options) w(`  - \`${o.value}\` ${o.label}`);
          }
          w();
          w('</details>');
          w();
        }
      }
    }
  }

  // Stage groups.
  const groupSets = site.stageGroups.shared
    ? [['clinical and pathological', site.stageGroups.shared]]
    : basesFor(site).map((b) => [b, stageRulesFor(site, b)]);
  for (const [label, rules] of groupSets) {
    w(`### Prognostic stage groups — ${label}`);
    w();
    w('Evaluated top to bottom, first match wins.');
    w();
    w('| # | When | T | N | M | Stage | Source |');
    w('|---|---|---|---|---|---|---|');
    rules.forEach((r, i) => {
      const when = r.when
        ? Object.entries(r.when).map(([k, v]) => `${k}: ${v.join('/')}`).join('; ')
        : '—';
      w(`| ${i + 1} | ${when} | ${fmt(r.T)} | ${fmt(r.N)} | ${fmt(r.M)} | **${r.stage}** | ${r.source} |`);
    });
    w();
  }

  // Survival sourcing.
  for (const basis of basesFor(site)) {
    const s = survivalFor(site.id, basis);
    if (!s) continue;
    if (basis !== basesFor(site)[0] && s === survivalFor(site.id, basesFor(site)[0])) continue;
    w(`### Survival figure — ${s.key}`);
    w();
    w(`- **Endpoint:** ${s.endpoint}${s.cohort ? ` (${s.cohort})` : ''}`);
    w(`- **Figure:** ${s.figure}`);
    w(`- **Citation:** ${s.citation}`);
    w(`- **Source:** <${s.url}>`);
    if (s.paperFile) w(`- **Paper (local copy):** \`${s.paperFile}\``);
    w(`- **Image file expected at:** \`assets/survival/${s.key}.png\``);
    if (Object.keys(s.stages).length) {
      w(`- **Published estimates:** ${Object.entries(s.stages).map(([k, v]) => `${k}: ${v}`).join('; ')}`);
    }
    if (s.stagesNote) w(`- **Note:** ${s.stagesNote}`);
    if (s.note) w(`- **Note:** ${s.note}`);
    if (s.pending) w(`- **Outstanding:** ${s.pending}`);
    w();
  }

  if (site.notes?.length) {
    w('### Notes and pitfalls shown to students');
    w();
    for (const n of site.notes) w(`- ${n}`);
    w();
  }
  w('---');
  w();
}

console.log(out.join('\n'));
